spring:
  application:
    name: pharmquest # ?????? ?? ??
  datasource:
    url: jdbc:mysql://localhost:3306/pharamPractice?useSSL=false&serverTimezone=UTC
    username: root
    password: 53099035
  jpa:
    hibernate:
      ddl-auto: update # ???? ?? ??/????
    database-platform: org.hibernate.dialect.MySQLDialect # MySQL Dialect ??
    show-sql: true # ???? SQL ??
    properties:
      hibernate:
        format_sql: true # ???? SQL ???
